# Generated by Django 5.2.1 on 2025-06-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis1Equipo1', models.IntegerField(default=0)),
                ('dis2Equipo1', models.IntegerField(default=0)),
                ('dis3Equipo1', models.IntegerField(default=0)),
                ('dis4Equipo1', models.IntegerField(default=0)),
                ('dis5Equipo1', models.IntegerField(default=0)),
                ('dis1Equipo2', models.IntegerField(default=0)),
                ('dis2Equipo2', models.IntegerField(default=0)),
                ('dis3Equipo2', models.IntegerField(default=0)),
                ('dis4Equipo2', models.IntegerField(default=0)),
                ('dis5Equipo2', models.IntegerField(default=0)),
            ],
        ),
    ]
